### ISSUE TITLE
Conjugator: Searchable Drop Down

### ISSUE THREAD

**Issue by dlothian** [dlothian/MichifConjugator#2]
Ionic doesn't have any built in searchable drop down list (?) so have to find a way that will not break after small version updates.

**Comment by dlothian** [comment]
Solution: Pop modal for verb searching. 

TBD: Should Verb searching be limited to searching by verb and not any type? (i.e., transitivity/animacy)

**Comment by eddieantonio** [comment]
Look at https://kawennonnis.ca/wordmaker for inspiration!

**Comment by eddieantonio** [comment]
> TBD: Should Verb searching be limited to searching by verb and not any type? (i.e., transitivity/animacy)

I think _in general_ this is a good idea, but we need Heather's input on how to express the concept of transitivity. Kawennón:nis has the convention of red/blue/purple words, but that convention comes from Owennatekha Brian Maracle's way of teaching Kanyen'kéha.

**Comment by dlothian** [comment]
> > TBD: Should Verb searching be limited to searching by verb and not any type? (i.e., transitivity/animacy)
> 
> I think _in general_ this is a good idea, but we need Heather's input on how to express the concept of transitivity. Kawennón:nis has the convention of red/blue/purple words, but that convention comes from Owennatekha Brian Maracle's way of teaching Kanyen'kéha.

kawennonis is not in ionic :cry:

**Comment by dlothian** [comment]
> Look at https://kawennonnis.ca/wordmaker for inspiration!

kawennonis is not in ionic cry
The search function does not work on mobile.

**Comment by dlothian** [comment]
Chose instead to have a pop up modal. Works well on web and mobile.

**Comment by dlothian** [comment]
Instead has pop up modal with live updating list. More usable imo.
