### ISSUE TITLE
Conj Backend: SQLITE (????)

### ISSUE THREAD

**Issue by dlothian** [dlothian/MichifConjugator#24]
Tried to follow this tutorial: https://www.youtube.com/watch?v=fZ4giHzXfSg&t=450s

And uh idk what's fundamentally different but everything else online says that what he's doing shouldn't work (at least on browser) and yet it does for him so Idk what that's about. We're gonna put a big ole pin in this and see if offline storage is easier using other more ionic ways.

RIP sql queries :crying_cat_face:

**Comment by eddieantonio** [comment]
According to this, it's supported on https://ionicframework.com/docs/native/sqlite#platforms

> - Android
> - iOS
> - macOS
> - Windows

It doesn't say browser...

**Comment by dlothian** [comment]
I've watch 1000 videos and confirmed, no browser :cry:

**Comment by dlothian** [comment]
Sqlite will be used to manipulate data but all in all be excluded from the rest of development
